spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/saga
    username: root
    password: Mysql@2022

# Axon Server Configuration
axon:
  axonserver:
    servers: localhost:8124
    name: notification-service

#configure specific port
server:
  port: 8080

# database configuration

